### ISSUE TITLE
templateEngine parameter is ignored

### ISSUE THREAD

**Issue by genemars** [paulcpederson/static-site#10]
I'm using version 1.3.2 from npm. From what I've understand `template.js` is looking for the `templateEngine` parameter in `context.templateEngine` while actually it seems to be placed in  `context.options.templateEngine`.
https://github.com/paulcpederson/static-site/blob/master/lib/template.js#L76
or am I doing something wrong?

**Comment by paulcpederson** [comment]
It should work when passed as an option to static site. There is an example of using a custom template engine inside the test suite, if that helps: https://github.com/paulcpederson/static-site/blob/master/test/template.js#L67

Are you running static site from the CLI or from the Node API?

**Comment by genemars** [comment]
Running from node API like this:
```js
staticSite({
    build: 'docs',
    source: 'source',
    ignore: ignoreList,
    helpers: ['helpers/subfolder_root.js'],
    files: ['html', 'css', 'js', 'md', 'svg'],
    templateEngine: 'helpers/render.js'
}, function(err, stats) {
    // stats -> {pages: [...], source: '', build: '', start: 1434175863750, end: 1434175863770, duration: 20}
    console.log(err, stats);
});
```

**Comment by paulcpederson** [comment]
That's a bug, will patch, thanks for reporting 👍

**Comment by genemars** [comment]
I was looking for a simple static-site generator like this one. It's versatile and I like it. So thank you, for quick reply also.

**Comment by paulcpederson** [comment]
@genemars ok, published `v1.3.3` which should hopefully fix, let me know if not!

**Comment by genemars** [comment]
It works :smiley:

**Comment by genemars** [comment]
Now I wonder. Is there a way to run the default template engine and then also the custom one? So one can implement his own custom tags and also have the default swig processing.

**Comment by paulcpederson** [comment]
I think the way to do this would be to just run swig yourself from your own custom template engine. You can control the flow, order, plugins, extensions, etc from your custom file. Basically just steal the parts of https://github.com/paulcpederson/static-site/blob/master/lib/template.js you need and put it after your custom engine.
