### ISSUE TITLE
swig is deprecated

### ISSUE THREAD

**Issue by ungoldman** [paulcpederson/static-site#9]
Looks like the maintainer took the gh-pages site offline and added a warning to the readme.

https://github.com/paularmstrong/swig

Bummer.

**Comment by paulcpederson** [comment]
yeah, will be moving to http://node-swig.github.io/swig-templates/ as soon as they publish

**Comment by paulcpederson** [comment]
update: https://www.npmjs.com/package/swig-templates is now published, I'll try to whip this up soon
